name: pop-tools-dev
channels:
  - conda-forge
  - numba
dependencies:
  - bottleneck
  - codecov
  - dask
  - docrep
  - nbsphinx
  - netcdf4
  - numba
  - pip
  - pooch
  - pytest-cov
  - pyyaml
  - scipy
  - xarray
  - xgcm
  - watermark
